dist:
  module: github.com/open-telemetry/opentelemetry-collector-contrib
  name: otelcol-custom
  description: Custom Collector with ALL contrib components + httpprocessor
  version: 0.1.0

processors:
  - gomod: github.com/koponk04/otel-custom-components v0.1.0
    import: github.com/koponk04/otel-custom-components/processor/httpprocessor
    path: ./
