receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Your custom processor
  httpprocessor:
    endpoint: "http://localhost:8080"
    headers:
      Authorization: "Bearer token123"
    timeout: "30s"
  
  # Batch processor from contrib
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  
  # Uncomment and configure if you have a backend
  # otlp:
  #   endpoint: "your-backend:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [httpprocessor, batch]
      exporters: [debug]
    
    metrics:
      receivers: [otlp]
      processors: [httpprocessor, batch]
      exporters: [debug]
    
    logs:
      receivers: [otlp]
      processors: [httpprocessor, batch]
      exporters: [debug]
